version: "3.8"

services:
  postgresprototipo:
    build: ./postgresPrototipo
    environment:
      - POSTGRES_PASSWORD=SENHASECRETA
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - postgresPrototipo_data:/var/lib/postgresql/data
    
  postgresdatabase:
    build: ./postgresDB
    environment:
      - POSTGRES_PASSWORD=SENHASECRETA
    ports:
      - "12345:5432"
      - "12346:5433"
    volumes:
      - postgresDatabase_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3333:3333"
    depends_on:
      - postgresprototipo
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=SENHASECRETA
      - DB_HOST=postgresprototipo
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - EXPRESS_PORT=3333

  front:
    build: ./front
    ports:
      - "5050:5050"
    depends_on:
      - backend
    environment:
      - DB_URL='http://127.0.0.1:3333'

volumes:
  postgresPrototipo_data:
  postgresDatabase_data: